### ISSUE TITLE
Improvement idea for \frac

### ISSUE THREAD

**Issue by alexandru-duca** [ray-pH/Nabla-TypeMath-android#6] opened 2023-09-16 23:32 UTC
|     Input     | Output [v1.3.2] | Suggested Output |
|:-------------:|:--------------:|:----------------:|
| .\frac{1}{2}. |     [¹]⁄[₂]    |         ½        |

**Comment by ray-pH** [comment] 2023-09-23 17:44
You've found a bug. It should be 1⁄2 without the square brackets. Will try to fix it asap

**Comment by ray-pH** [comment] 2023-09-23 17:53
I choose the fraction slash unicode (U+2044) [⁄] because it's more general, and you don't have to handle each particular fraction that exists in Unicode (¼ ½ ¾ ⅐ ⅑ ⅒ ⅓ ⅔ ⅕ ⅖ ⅗ ⅘ ⅙ ⅚ ⅛ ⅜ ⅝ ⅞ ⅟ ↉).

And also, 1 + ⁄ + 2 = 1⁄2 (three separate characters) will render exactly the same as ½ (U+00BD) for many systems.

**Comment by alexandru-duca** [comment] 2023-09-23 20:12
Thanks for elaborating. On my phone, 1⁄2 (which looks more like ¹⁄₂) and ½ render differently (the latter looking neater). I suggest outputting a Unicode-fraction if one exists and three seperate characters if one doesn't exist. I also suggest removing the brackets if the nominator (or denominator) consists of only one symbol.

|     Input     | Output [v1.3.2] | Suggested Output |
|:-------------:|:--------------:|:----------------:|
| .\frac{1}{2}. |     [¹]⁄[₂]    |         ½        |
| .\frac{1}{9}. |     [¹]⁄[₉]     |         ¹⁄₉        |

**Comment by ray-pH** [comment] 2023-10-09 18:42
Sorry for taking a while, I've only recently had the time to address the issue. The problem is now fixed in v1.3.3

**Closed by ray-pH** 2023-10-09 18:42 UTC
